name: Deploy with secrets

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # ЗАСТАВЛЯЕМ ИСПОЛЬЗОВАТЬ НОВУЮ ВЕРСИЮ NODE.JS
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      
      - name: Replace tokens in index.html
        run: |
          sed -i 's/__TELEGRAM_BOT_TOKEN__/${{ secrets.TELEGRAM_BOT_TOKEN }}/g' index.html
          sed -i 's/__TELEGRAM_CHAT_ID__/${{ secrets.TELEGRAM_CHAT_ID }}/g' index.html
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
